"""
frontend/app.py

MedGuide AI - Multimodal Healthcare Assistant (Frontend Prototype)

This is a FRONTEND-ONLY prototype for a final-year project. All responses
are generated by local mock logic (see generate_response below). No real
medical AI model is used, and no external APIs are called.

Run with:
    streamlit run frontend/app.py
"""

import sys
import os
from datetime import datetime

import streamlit as st

# Allow importing the "safety" package from the project root when this
# file is run directly via `streamlit run frontend/app.py`.
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from safety.pipeline import run_safety_pipeline
from safety.triage import SELF_CARE, CONSULT_DOCTOR, EMERGENCY


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="MedGuide AI",
    page_icon="🩺",
    layout="centered",
    initial_sidebar_state="expanded",
)


# ============================================================
# STYLES
# ============================================================

def load_styles():
    st.markdown(
        """
        <style>
            /* ---------- General layout ---------- */
            .block-container {
                max-width: 780px;
                padding-top: 1.5rem;
                padding-bottom: 6rem;
            }

            #MainMenu, footer, header {visibility: hidden;}

            html, body, [class*="css"] {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                             Roboto, Helvetica, Arial, sans-serif;
            }

            /* ---------- Header ---------- */
            .app-header {
                display: flex;
                flex-direction: column;
                gap: 4px;
                padding-bottom: 12px;
                border-bottom: 1px solid #E5E7EB;
                margin-bottom: 20px;
            }

            .app-title-row {
                display: flex;
                align-items: center;
                justify-content: space-between;
            }

            .app-title {
                font-size: 1.6rem;
                font-weight: 700;
                color: #14342B;
                margin: 0;
            }

            .app-subtitle {
                font-size: 0.95rem;
                color: #5B6B66;
                margin: 0;
            }

            .status-pill {
                display: inline-flex;
                align-items: center;
                gap: 6px;
                background: #EAF6EF;
                color: #1E7A4C;
                font-size: 0.78rem;
                font-weight: 600;
                padding: 4px 10px;
                border-radius: 999px;
                border: 1px solid #CDEBD8;
                white-space: nowrap;
            }

            .status-dot {
                width: 7px;
                height: 7px;
                border-radius: 50%;
                background: #2FA866;
                display: inline-block;
            }

            .safety-banner {
                margin-top: 10px;
                background: #F7F8F6;
                border: 1px solid #E5E7EB;
                border-left: 3px solid #2E7D5B;
                border-radius: 8px;
                padding: 9px 14px;
                font-size: 0.83rem;
                color: #4B5563;
            }

            /* ---------- Welcome state ---------- */
            .welcome-wrap {
                text-align: center;
                padding: 28px 10px 8px 10px;
            }

            .welcome-title {
                font-size: 1.4rem;
                font-weight: 700;
                color: #1F2937;
                margin-bottom: 6px;
            }

            .welcome-subtitle {
                font-size: 0.95rem;
                color: #6B7280;
                max-width: 480px;
                margin: 0 auto 22px auto;
                line-height: 1.5;
            }

            .example-label {
                font-size: 0.78rem;
                font-weight: 600;
                letter-spacing: 0.03em;
                color: #9CA3AF;
                text-transform: uppercase;
                margin-bottom: 10px;
                text-align: left;
            }

            /* ---------- Chat bubbles ---------- */
            .chat-row {
                display: flex;
                margin-bottom: 14px;
            }

            .chat-row.user {
                justify-content: flex-end;
            }

            .chat-row.assistant {
                justify-content: flex-start;
            }

            .bubble-user {
                background: #14342B;
                color: #FFFFFF;
                padding: 11px 16px;
                border-radius: 16px 16px 4px 16px;
                max-width: 78%;
                font-size: 0.94rem;
                line-height: 1.5;
            }

            .bubble-meta {
                font-size: 0.7rem;
                color: #9CA3AF;
                margin-top: 4px;
            }

            /* ---------- Response card ---------- */
            .response-card {
                background: #FFFFFF;
                border: 1px solid #E5E7EB;
                border-radius: 14px;
                padding: 18px 20px;
                max-width: 88%;
                box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
            }

            .response-section {
                margin-bottom: 14px;
            }

            .response-section:last-child {
                margin-bottom: 0;
            }

            .response-label {
                font-size: 0.72rem;
                font-weight: 700;
                letter-spacing: 0.04em;
                text-transform: uppercase;
                color: #9CA3AF;
                margin-bottom: 4px;
            }

            .response-value {
                font-size: 0.95rem;
                color: #1F2937;
                line-height: 1.55;
            }

            .response-value ul {
                margin: 4px 0 0 0;
                padding-left: 20px;
            }

            .response-value li {
                margin-bottom: 3px;
            }

            .condition-name {
                font-size: 1.05rem;
                font-weight: 700;
                color: #14342B;
            }

            /* ---------- Urgency badges ---------- */
            .urgency-badge {
                display: inline-flex;
                align-items: center;
                gap: 6px;
                font-size: 0.8rem;
                font-weight: 700;
                padding: 5px 12px;
                border-radius: 8px;
                letter-spacing: 0.02em;
            }

            .urgency-self-care {
                background: #EAF6EF;
                color: #1E7A4C;
                border: 1px solid #CDEBD8;
            }

            .urgency-consult {
                background: #FFF6E5;
                color: #B4740E;
                border: 1px solid #F5E1B3;
            }

            .urgency-emergency {
                background: #FDECEC;
                color: #C0322A;
                border: 1px solid #F5C6C3;
            }

            .emergency-box {
                background: #FDECEC;
                border: 1px solid #F5C6C3;
                border-radius: 10px;
                padding: 12px 14px;
                margin-top: 6px;
                color: #8A211B;
                font-weight: 600;
                font-size: 0.92rem;
            }

            .disclaimer-box {
                margin-top: 6px;
                font-size: 0.78rem;
                color: #9CA3AF;
                border-top: 1px dashed #E5E7EB;
                padding-top: 10px;
                line-height: 1.5;
            }

            /* ---------- Image preview card ---------- */
            .image-card {
                background: #F7F8F6;
                border: 1px solid #E5E7EB;
                border-radius: 12px;
                padding: 12px 14px;
                margin-top: 8px;
                font-size: 0.85rem;
                color: #4B5563;
            }

            .image-received {
                color: #1E7A4C;
                font-weight: 600;
                font-size: 0.85rem;
                margin-top: 6px;
            }

            /* ---------- Sidebar ---------- */
            section[data-testid="stSidebar"] {
                background: #FBFBFA;
            }

            .sidebar-title {
                font-size: 1.15rem;
                font-weight: 700;
                color: #14342B;
                margin-bottom: 2px;
            }

            .sidebar-subtitle {
                font-size: 0.82rem;
                color: #6B7280;
                margin-bottom: 18px;
            }

            .sidebar-section-title {
                font-size: 0.75rem;
                font-weight: 700;
                letter-spacing: 0.04em;
                text-transform: uppercase;
                color: #9CA3AF;
                margin-top: 18px;
                margin-bottom: 8px;
            }

            .sidebar-step {
                font-size: 0.85rem;
                color: #374151;
                margin-bottom: 6px;
                line-height: 1.4;
            }

            .sidebar-safety {
                background: #FFFFFF;
                border: 1px solid #E5E7EB;
                border-left: 3px solid #2E7D5B;
                border-radius: 8px;
                padding: 10px 12px;
                font-size: 0.8rem;
                color: #4B5563;
                line-height: 1.5;
            }
        </style>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# MOCK BACKEND (future integration point)
# ============================================================

def generate_response(symptoms: str, image=None) -> dict:
    """
    Mock backend response generator.

    THIS IS THE FUTURE INTEGRATION POINT.

    Later, this function's body will be replaced with a call into the
    real pipeline: preprocessing -> multimodal encoder -> RAG retrieval
    -> grounded response generation -> safety/triage filter. The return
    shape below is designed to match what that pipeline is expected to
    produce, so the frontend will not need to change.

    For now, it uses simple keyword-based mock logic purely for
    demonstration purposes. This is NOT a real diagnostic algorithm.
    """
    text = (symptoms or "").lower()

    emergency_terms = [
        "chest pain", "difficulty breathing", "can't breathe",
        "cannot breathe", "shortness of breath", "severe bleeding",
        "heavy bleeding", "loss of consciousness", "unconscious",
        "fainted", "stroke", "slurred speech", "seizure",
        "severe allergic reaction", "anaphylaxis", "not breathing",
        "blue lips", "crushing pain",
    ]

    fever_cough_terms = ["fever", "cough"]

    headache_terms = ["headache", "mild headache", "stress", "dehydration", "tired"]

    if any(term in text for term in emergency_terms):
        response = {
            "response": (
                "The symptoms you've described may indicate a serious medical "
                "emergency."
            ),
            "possible_conditions": ["Potential medical emergency"],
            "urgency": EMERGENCY,
            "what_it_may_mean": (
                "Symptoms like these can sometimes be associated with serious "
                "conditions that need immediate attention. This assistant "
                "cannot confirm what is happening, but the combination of "
                "symptoms you described should not be ignored."
            ),
            "recommended_action": (
                "Seek emergency medical attention immediately. Call your "
                "local emergency number or go to the nearest emergency room "
                "right away. Do not wait to see if symptoms improve."
            ),
            "warning_signs": [
                "Symptoms getting worse or spreading",
                "New or worsening pain",
                "Any loss of consciousness",
            ],
            "sources": [],
        }

    elif all(term in text for term in fever_cough_terms):
        response = {
            "response": (
                "Your combination of symptoms may be consistent with a "
                "respiratory infection."
            ),
            "possible_conditions": ["Respiratory infection"],
            "urgency": CONSULT_DOCTOR,
            "what_it_may_mean": (
                "Fever together with a cough can be caused by a range of "
                "respiratory infections, from mild viral illnesses to "
                "conditions that need medical treatment. It is difficult to "
                "know which one without an examination."
            ),
            "recommended_action": (
                "Consider speaking with a healthcare professional, "
                "especially if your fever is high, lasts more than a couple "
                "of days, or is accompanied by other symptoms. Rest and "
                "stay hydrated in the meantime."
            ),
            "warning_signs": [
                "Difficulty breathing or shortness of breath",
                "Fever above 39.4°C (103°F) or lasting more than 3 days",
                "Chest pain or confusion",
            ],
            "sources": [],
        }

    elif any(term in text for term in headache_terms) and "chest pain" not in text:
        response = {
            "response": (
                "Your symptoms may be consistent with a tension-type "
                "headache."
            ),
            "possible_conditions": ["Tension-type headache"],
            "urgency": SELF_CARE,
            "what_it_may_mean": (
                "Tension-type headaches are common and are often linked to "
                "stress, dehydration, poor sleep, or eye strain. They "
                "usually feel like a dull, steady pressure rather than a "
                "sharp pain."
            ),
            "recommended_action": (
                "Consider resting in a quiet space, drinking water, and "
                "monitoring how you feel over the next few hours. Over-the-"
                "counter pain relief may help, but please follow the "
                "label instructions or ask a pharmacist."
            ),
            "warning_signs": [
                "Sudden, severe headache unlike any before",
                "Headache with fever, stiff neck, or confusion",
                "Headache following a head injury",
            ],
            "sources": [],
        }

    else:
        response = {
            "response": (
                "I'd need a bit more information to provide useful "
                "preliminary guidance."
            ),
            "possible_conditions": [],
            "urgency": CONSULT_DOCTOR,
            "what_it_may_mean": (
                "Your description doesn't yet give me enough detail to "
                "narrow things down, even at a preliminary level."
            ),
            "recommended_action": (
                "Please share when the symptoms started, how severe they "
                "are, and any other symptoms you've noticed. This will "
                "help provide more relevant guidance."
            ),
            "warning_signs": [
                "Symptoms that suddenly worsen",
                "New symptoms appearing alongside the original ones",
            ],
            "sources": [],
        }

    if image is not None:
        response["image_note"] = (
            "Image uploaded successfully. Multimodal image analysis will "
            "be connected during backend integration."
        )

    # Run the mock response through the (placeholder) safety pipeline.
    response = run_safety_pipeline(symptoms, response)

    return response


# ============================================================
# UI COMPONENTS
# ============================================================

def render_header():
    st.markdown(
        """
        <div class="app-header">
            <div class="app-title-row">
                <div>
                    <p class="app-title">MedGuide AI</p>
                    <p class="app-subtitle">Multimodal Healthcare Assistant</p>
                </div>
                <div class="status-pill">
                    <span class="status-dot"></span> AI Assistant Online
                </div>
            </div>
            <div class="safety-banner">
                Preliminary guidance only. This assistant does not replace
                professional medical diagnosis.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_sidebar():
    with st.sidebar:
        st.markdown('<p class="sidebar-title">MedGuide AI</p>', unsafe_allow_html=True)
        st.markdown(
            '<p class="sidebar-subtitle">Your multimodal healthcare assistant</p>',
            unsafe_allow_html=True,
        )

        st.markdown('<p class="sidebar-section-title">How it works</p>', unsafe_allow_html=True)
        steps = [
            "Describe your symptoms",
            "Upload an image (optional)",
            "AI analyzes the available information",
            "Relevant medical knowledge is retrieved",
            "Grounded guidance is generated",
            "Safety and urgency checks are applied",
        ]
        for i, step in enumerate(steps, start=1):
            st.markdown(f'<p class="sidebar-step">{i}. {step}</p>', unsafe_allow_html=True)

        st.markdown('<p class="sidebar-section-title">Safety notice</p>', unsafe_allow_html=True)
        st.markdown(
            """
            <div class="sidebar-safety">
                This tool provides preliminary guidance only and should not
                replace a qualified healthcare professional.
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("Clear Chat", use_container_width=True):
            clear_chat()
            st.rerun()


EXAMPLE_PROMPTS = [
    "What could be causing my headache?",
    "I have a red rash on my arm",
    "I've had a fever and cough for 3 days",
    "I have stomach pain after eating",
]


def render_welcome():
    st.markdown(
        """
        <div class="welcome-wrap">
            <p class="welcome-title">How can I help you today?</p>
            <p class="welcome-subtitle">
                Describe your symptoms in your own words. You can also
                upload a medical image for multimodal analysis.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown('<p class="example-label">Try an example</p>', unsafe_allow_html=True)
    cols = st.columns(2)
    for i, prompt in enumerate(EXAMPLE_PROMPTS):
        with cols[i % 2]:
            if st.button(prompt, key=f"example_{i}", use_container_width=True):
                submit_message(prompt)
                st.rerun()


def render_chat_message(message: dict):
    role = message["role"]
    timestamp = message.get("time", "")

    if role == "user":
        st.markdown(
            f"""
            <div class="chat-row user">
                <div>
                    <div class="bubble-user">{message["content"]}</div>
                    <div class="bubble-meta" style="text-align:right;">{timestamp}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        if message.get("image"):
            render_uploaded_image(message["image"], inline=True)
    else:
        render_response_card(message["content"], timestamp)


def urgency_badge_html(urgency: str) -> str:
    if urgency == EMERGENCY:
        css_class = "urgency-emergency"
        label = "⚠ EMERGENCY"
    elif urgency == CONSULT_DOCTOR:
        css_class = "urgency-consult"
        label = "CONSULT DOCTOR"
    else:
        css_class = "urgency-self-care"
        label = "SELF-CARE"

    return f'<span class="urgency-badge {css_class}">{label}</span>'


def render_response_card(response: dict, timestamp: str = ""):
    urgency = response.get("urgency", SELF_CARE)
    conditions = response.get("possible_conditions", [])
    condition_text = conditions[0] if conditions else "General guidance"

    warning_signs = response.get("warning_signs", [])
    warning_items = "".join(f"<li>{w}</li>" for w in warning_signs)

    emergency_block = ""
    if urgency == EMERGENCY:
        emergency_block = f"""
        <div class="emergency-box">
            🚨 {response.get('recommended_action', 'Seek emergency medical attention immediately.')}
        </div>
        """

    image_note_block = ""
    if response.get("image_note"):
        image_note_block = f"""
        <div class="response-section">
            <div class="response-label">Image note</div>
            <div class="response-value">{response['image_note']}</div>
        </div>
        """

    card_html = f"""
    <div class="chat-row assistant">
        <div class="response-card">
            <div class="response-section">
                <div class="response-label">Possible condition</div>
                <div class="condition-name">{condition_text}</div>
            </div>

            <div class="response-section">
                <div class="response-label">What this may mean</div>
                <div class="response-value">{response.get('what_it_may_mean', response.get('response', ''))}</div>
            </div>

            <div class="response-section">
                <div class="response-label">Urgency</div>
                {urgency_badge_html(urgency)}
                {emergency_block}
            </div>

            <div class="response-section">
                <div class="response-label">Recommended action</div>
                <div class="response-value">{response.get('recommended_action', '')}</div>
            </div>

            <div class="response-section">
                <div class="response-label">Watch for</div>
                <div class="response-value"><ul>{warning_items}</ul></div>
            </div>

            {image_note_block}

            <div class="disclaimer-box">
                This is preliminary AI-generated guidance and does not
                constitute a medical diagnosis. If you are concerned about
                your symptoms, consult a qualified healthcare professional.
            </div>
        </div>
    </div>
    """
    st.markdown(card_html, unsafe_allow_html=True)


def render_uploaded_image(image_file, inline: bool = False):
    st.markdown('<div class="image-card">Medical image</div>', unsafe_allow_html=True)
    st.image(image_file, use_container_width=True)
    st.markdown('<div class="image-received">✓ Image received</div>', unsafe_allow_html=True)
    if not inline:
        st.caption(
            "Multimodal image analysis will be connected during backend "
            "integration."
        )


def clear_chat():
    st.session_state.messages = []
    st.session_state.pending_prompt = None


def submit_message(text: str, image=None):
    """Add a user message and the mock assistant response to history."""
    now = datetime.now().strftime("%I:%M %p")

    st.session_state.messages.append(
        {"role": "user", "content": text, "time": now, "image": image}
    )

    response = generate_response(text, image)

    st.session_state.messages.append(
        {"role": "assistant", "content": response, "time": now}
    )


# ============================================================
# MAIN APP
# ============================================================

def main():
    load_styles()

    if "messages" not in st.session_state:
        st.session_state.messages = []

    render_header()
    render_sidebar()

    if len(st.session_state.messages) == 0:
        render_welcome()
    else:
        for message in st.session_state.messages:
            render_chat_message(message)

    st.markdown("<br>", unsafe_allow_html=True)

    with st.form(key="input_form", clear_on_submit=True):
        symptom_text = st.text_area(
            "Describe your symptoms here...",
            placeholder="Describe your symptoms here...",
            label_visibility="collapsed",
            height=90,
        )

        uploaded_image = st.file_uploader(
            "Upload medical image (optional)",
            type=["png", "jpg", "jpeg"],
            help="Optional. Supported formats: PNG, JPG, JPEG.",
        )

        submitted = st.form_submit_button("Send", use_container_width=True)

    if submitted and (symptom_text.strip() or uploaded_image is not None):
        submit_message(symptom_text.strip(), uploaded_image)
        st.rerun()


if __name__ == "__main__":
    main()
